### ISSUE TITLE
Is this still up to date?

### ISSUE THREAD

**Issue by Avnsx** [MegrezZhu/nord-proxy-balancer#1]
I've just tried to do:

https://github.com/MegrezZhu/nord-proxy-balancer/blob/3890348c89dbe54b3bca6a94f34551e80fc4223a/nordapi/nordtoy.py#L41

it doesn't seem to give me any ``response.text`` passing my email for ``ns.userdetails[0]``; just empty response

@MegrezZhu

**Comment by MegrezZhu** [comment]
I'm not maintaining this repo any longer, and the scripts under `nordapi` was found on internet and I have no clue on where to find the updated version (if there's any).
